# Generated by Django 5.2 on 2025-05-12 09:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os', models.CharField(max_length=255)),
                ('os_version', models.CharField(max_length=255)),
                ('platform', models.CharField(max_length=512)),
                ('architecture', models.CharField(max_length=512)),
                ('hostname', models.CharField(blank=True, max_length=512, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('cpu_brand', models.CharField(max_length=255)),
                ('cpu_cores_physical', models.PositiveIntegerField(default=0)),
                ('cpu_cores_logical', models.PositiveIntegerField(default=0)),
                ('cpu_frequency_mhz', models.FloatField(default=0)),
                ('ram', models.CharField(max_length=512)),
                ('storage', models.CharField(max_length=512)),
                ('network_interfaces', models.TextField()),
                ('gpu_name', models.CharField(blank=True, max_length=512, null=True)),
                ('gpu_memory', models.CharField(blank=True, max_length=512, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('os', models.IntegerField(choices=[(0, 'UNIX'), (1, 'Linux'), (2, 'Windows'), (3, 'Mac OS')], default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('safety', models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('exe', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_time', models.DateTimeField(auto_now_add=True)),
                ('cpu_load', models.FloatField(default=0, help_text='Load in percents')),
                ('ram_load', models.FloatField(default=0, help_text='Load in bytes')),
                ('network_load', models.FloatField(default=0, help_text='Load in bytes')),
                ('gpu_load', models.FloatField(blank=True, default=0, help_text='Load in bytes', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProcessStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_time', models.DateTimeField(auto_now_add=True)),
                ('pid', models.IntegerField()),
                ('exe', models.CharField(blank=True, max_length=512, null=True)),
                ('name', models.CharField(blank=True, max_length=512, null=True)),
                ('username', models.CharField(blank=True, max_length=512, null=True)),
                ('cmdline', models.TextField(blank=True, max_length=512, null=True)),
                ('stat', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.stat')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
