# Generated by Django 5.2 on 2025-05-13 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_stat_computer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stat',
            new_name='ComputerStat',
        ),
        migrations.RemoveField(
            model_name='processstat',
            name='stat',
        ),
        migrations.AddField(
            model_name='processstat',
            name='cpu_load',
            field=models.FloatField(default=0, help_text='Load in percents'),
        ),
        migrations.AddField(
            model_name='processstat',
            name='gpu_load',
            field=models.FloatField(blank=True, default=0, help_text='Load in bytes', null=True),
        ),
        migrations.AddField(
            model_name='processstat',
            name='network_load',
            field=models.FloatField(default=0, help_text='Load in bytes'),
        ),
        migrations.AddField(
            model_name='processstat',
            name='ram_load',
            field=models.FloatField(default=0, help_text='Load in bytes'),
        ),
    ]
