# Generated by Django 5.2 on 2025-05-13 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_stat_computerstat_remove_processstat_stat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computerstat',
            name='id',
        ),
        migrations.RemoveField(
            model_name='processstat',
            name='id',
        ),
        migrations.AlterField(
            model_name='computerstat',
            name='record_time',
            field=models.DateTimeField(auto_now_add=True, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='processstat',
            name='record_time',
            field=models.DateTimeField(auto_now_add=True, primary_key=True, serialize=False, unique=True),
        ),
    ]
