# Generated by Django 5.2 on 2025-05-13 14:34
import datetime
from django.db import migrations, models


def set_initial_status(apps, schema_editor):
    for k in ('ComputerStat', 'ProcessStat'):
        MyModel = apps.get_model('main', k)
        models = MyModel.objects.all()
        for m in models:
            m.record_time_timestamp = int(m.record_time.timestamp())
            m.save()

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_computerstat_id_remove_processstat_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='computerstat',
            name='record_time_timestamp',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='processstat',
            name='record_time_timestamp',
            field=models.BigIntegerField(default=0),
        ),
        migrations.RunPython(set_initial_status)
    ]
