# Generated by Django 5.2 on 2025-05-13 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_computerstat_record_time_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computerstat',
            name='record_time',
            field=models.DateTimeField(auto_now_add=True, unique=True),
        ),
        migrations.AlterField(
            model_name='computerstat',
            name='record_time_timestamp',
            field=models.BigIntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='processstat',
            name='record_time',
            field=models.DateTimeField(auto_now_add=True, unique=True),
        ),
        migrations.AlterField(
            model_name='processstat',
            name='record_time_timestamp',
            field=models.BigIntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
